Repository CruGlobal/plugin_ABDesigner, pull requests merged in 2023-09, with the labels that each got.

#212 Auto Version
  .github/workflows/dispatch-web-update.yml
  .github/workflows/e2e-test.yml
  .github/workflows/merging-rules.yml
  .github/workflows/pr-label-check.yml
  .github/workflows/pr-merge-release.yml
  README.md
Labels: major

#213 fix dispatch location
  .github/workflows/dispatch-web-update.yml
Labels: patch

#215 *Fix compatible filter settings of Form connect element
  src/rootPages/Designer/properties/views/ABViewFormConnect.js
Labels: patch

#216 *Update load application list from myapps url in the Designer page
  src/rootPages/Designer/ui_choose_list.js
Labels: enhancement, minor
