Repository CruGlobal/plugin_ABDesigner, pull requests merged in 2024-11, with the labels that each got.

#270 *Fix [Current User] option in Record Rule
  src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionObjectUpdater.js
Labels: patch

#272 Current Netsuite API code
  package-lock.json
  package.json
  src/rootPages/Designer/properties/dataFields/ABFieldConnect.js
  src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionObjectUpdater.js
  src/rootPages/Designer/ui_work_object_list_newObject.js
  src/rootPages/Designer/ui_work_object_list_newObject_api_read_response.js
  src/rootPages/Designer/ui_work_object_list_newObject_netsuite.js
  src/rootPages/Designer/ui_work_object_list_newObject_netsuite_connections.js
  src/rootPages/Designer/ui_work_object_list_newObject_netsuite_credentials.js
  src/rootPages/Designer/ui_work_object_list_newObject_netsuite_dataTest.js
  src/rootPages/Designer/ui_work_object_list_newObject_netsuite_fields.js
  src/rootPages/Designer/ui_work_object_list_newObject_netsuite_tables.js
  src/rootPages/Designer/ui_work_object_workspace.js
  src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
Labels: enhancement

#276 Add widget to set cursor in DC
  src/rootPages/Designer/editors/EditorManager.js
  src/rootPages/Designer/editors/views/ABViewDataSelect.js
  src/rootPages/Designer/properties/PropertyManager.js
  src/rootPages/Designer/properties/views/ABViewDataSelect.js
Labels: minor

#278 +Add hidden fields setting
  src/rootPages/Designer/properties/views/ABViewCSVExporter.js
Labels: patch
