Repository CruGlobal/plugin_ABDesigner, pull requests merged in 2024-01, with the labels that each got.

#227 *Fix the query workspace page
  src/rootPages/Designer/ui_work_query_workspace_design.js
Labels: patch

#228 Implement linked cursor option in DC builder page
  src/rootPages/Designer/ui_work_datacollection_workspace.js
  src/rootPages/Designer/ui_work_datacollection_workspace_linked_dc.js
Labels: enhancement, patch

#229 support datetime in calculate field
  src/rootPages/Designer/properties/dataFields/ABFieldCalculate.js
Labels: patch

#230 Jh/performance
  index.js
Labels: minor
